#application.yml
spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    fetch-remote-regions-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
