spring:
  application:
    name: Config-Server
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    fetch-remote-regions-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
